name: 'codeql-sarif-precision-annotator'
description:
  'Enhance CodeQL SARIF results file to include a tag with the query precision.'
author: '@felickz'
inputs:
  sarif_file:
    required: true
    description: 'The CodeQL SARIF result file'
  output_file:
    required: true
    description: 'The output SARIF file path'
runs:
  using: node20
  main: dist/index.js
